### ISSUE TITLE
Cannot go to next task if I used Peek solution before

### ISSUE THREAD

**Issue by jiridanek** [jetbrains-academy/rustlings-course#133]
Clicking the Next navigation button or the navigation arrows on top of the task pane stops working, if I click the Peek solution immediately before.

Steps to reproduce:

1. Open task
2. Solve task, click Check, get green Done checkmark
3. Click Peek solution to compare with example solution (do not close the diff view in edit pane, immediately go to next step)
4. Click Next, and nothing happens

[idea.log.tail.txt](https://github.com/jetbrains-academy/rustlings-course/files/8619647/idea.log.tail.txt)

```
IntelliJ IDEA 2022.1.1 Preview (Ultimate Edition)
Build #IU-221.5591.19, built on April 28, 2022
Licensed to Jiri Daněk
Subscription is active until October 14, 2022.
Runtime version: 11.0.14.1+1-b2043.45 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.17.3-302.fc36.x86_64
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Non-Bundled Plugins:
    org.rust.lang (0.4.170.4601-221-nightly)
    org.jetbrains.plugins.go-template (221.5591.19)
    org.jetbrains.plugins.go (221.5591.19)
    name.kropp.intellij.makefile (221.5591.19)
    com.jetbrains.plugins.ini4idea (221.5591.19)
    com.jetbrains.edu (2022.4-2022.1-218)
    com.intellij.nativeDebug (221.5591.19)
    org.asciidoctor.intellij.asciidoc (0.37.17)
    dev.blachut.svelte.lang (0.22.0)
    Pythonid (221.5591.19)
    AceJump (3.8.7)

Kotlin: 221-1.6.21-release-337-IJ5591.19
Current Desktop: KDE
```

**Comment by igalimov** [comment]
Hi @jiridanek! I've filed a new issue in our tracker for you: https://youtrack.jetbrains.com/issue/EDU-5032/.
I would suggest adding this issue to your watch list to be 100% sure that you won't miss any updates.
