### ISSUE TITLE
Bug report from a user: Understanding Ownership / What is ownership / Moving Ownership

### ISSUE THREAD

**Issue by sofiiako** [jetbrains-academy/rustlings-course#162]
No Images rendered in the course description
The Rust Programming Language has information in images about memory layout which aren't rendered in the IDE. The images on the TRPL site carry a lot of information and it would be nice for them to render to the IDE. Thanks

**Comment by sofiiako** [comment]
@Geravant I could not reproduce this. Could you try please?

**Comment by Geravant** [comment]
@sofiiako can't reproduce it either
![image](https://user-images.githubusercontent.com/29254650/188198149-cd600bdb-3e11-4cec-9099-4f916e75d841.png)
I suggest we close.
