### ISSUE TITLE
Hint Buttons Do Not Work

### ISSUE THREAD

**Issue by JosephTLyons** [jetbrains-academy/rustlings-course#17]
I'm taking the Rust course and the button for Tips seems to be broken.  I am not able to click on it / nothing happens when it is clicked.

I'm using:

macOS 10.15.2
IntelliJ 2019.3.1
Rust 1.40
IntelliJ Rust Plugin 0.2.112.2148-193
IntelliJ EduTools 3.2-2019.3-3686

**Comment by igalimov** [comment]
Hello @JosephTLyons,
Thank you for your feedback!

I was unable to reproduce the issue on my machine, where I have the same versions of macOS and IntelliJ IDEA.
Do you have this issue with all the hints across the course or with specific ones?

**Comment by JosephTLyons** [comment]
Hmm, I'm not sure what the difference is now, but I can't seem to reproduce it.  I'll close this for now and if I find a way to reproduce, I'll report it again or post here.
