### ISSUE TITLE
Special characters are displayed as HTML character entities

### ISSUE THREAD

**Issue by Bragolgirith** [jetbrains-academy/rustlings-course#18]
Various special characters are displayed as HTML character entities inside the "Task Description" window, e.g. 
- `&amp;` instead of `&`
- `&lt;`  instead of `<`

Using:

> IntelliJ IDEA 2019.3.1 (Ultimate Edition)
> Build #IU-193.5662.53, built on December 18, 2019
> Windows 10 10.0

**Comment by arik-so** [comment]
I'm experiencing the same issue on Catalina, with the following build and config:

> CLion 2019.3.1
> Build #CL-193.5233.144, built on December 6, 2019
> Runtime version: 11.0.4+10-b520.11 x86_64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> macOS 10.15.2
> GC: ParNew, ConcurrentMarkSweep
> Memory: 1987M
> Cores: 16
> Registry: run.processes.with.pty=TRUE
> Non-Bundled Plugins: com.intellij.clion-swift, org.toml.lang, org.rust.lang, com.jetbrains.edu, org.editorconfig.editorconfigjetbrains

**Comment by igalimov** [comment]
Hello @Bragolgirith and @arik-so,

This is a known issue, it has been fixed, and we are currently testing it.
The fix should be included in the nearest update of the EduTools plugin.

Please keep up with our announcements.

**Comment by megaserg** [comment]
Hi @Geravant! Is this problem fixed or this is just an issue cleanup? I still observed the issue on the latest IDEA+Rust plugin+Edutools plugin+Rustilings course about a month ago.

**Comment by Geravant** [comment]
@megaserg , hi!
The course was updated and reworked in the past few months to catch up with the source 4.3.0 version. 
Most of the task descriptions were updated along the way. It included a hunt for the misspelled or misrendered entities, e.g. [this](https://github.com/jetbrains-academy/rustlings-course/commit/a4133accbf6c1a4966a140c5813d5561f0734e94#diff-593c6aa3a9b140e8d382cb966fe4b9b907d658bffdc99f54e4dd7221514b8989) and [this](https://github.com/jetbrains-academy/rustlings-course/commit/f660411d1049547f665535f8cf44c6cedaea2734#diff-db6dd28d9d104c7dab760d5cf70a22120b78524e26d5f29843a499b8ef1e73cb) commits. 
At the moment we did not find any remaining rogue symbols. Unfortunately, there will always be a chance, as the content will continue to evolve. We will try to provide a better quality of a learner's experience. If such an issue is to come up again - feel free to reopen this.

Note, that the updated version of the course was released on the new platform and is available at https://plugins.jetbrains.com/plugin/16631-rustlings or via IDE: Learn and Teach -> Browse Courses -> Marketplace
Unfortunately, the old version stored at https://stepik.org/course/59778 will no longer be updated (thus it will not have the improvements discussed).

Thank you for your feedback and your concern, we do genuinely appreciate it.

**Comment by megaserg** [comment]
I can confirm that the latest IDEA + EduTools + that updated Rustlings course doesn't have the issue anymore. Thanks so much!
