### ISSUE TITLE
Check nopt working  Common Programming Concepts / Repetitions / Print Months

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/rustlings-course#180]
The IDE sometimes detects an encoded char in the output. Sometimes it also detects additional spaces after the month names which cause the check to fail.
Expected
January
February
March
April
May
June
July
August
September
October
November
December

Actual:
January
February 
March    
April    
May      
June     
July     
August   
September
October  
November 
December 

Actual (sometimes additinoal chars):
January[54X
February[53X
March[56X
April[56X
May[58X
June[57X
July[57X
August[55X
September[52X
October[54X
November[53X
December[53X
[?25h

**Comment by sofiiako** [comment]
Possibly related to this https://youtrack.jetbrains.com/issue/EDU-5123/Some-unicode-characters-are-not-properly-processed-by-checker

**Comment by Geravant** [comment]
Might be fixed by [this](https://youtrack.jetbrains.com/issue/EDU-5608/java.lang.NoSuchMethodError-on-checking-Rust-projects).
