### ISSUE TITLE
Possible incorrect parent module Modules / Modules / Starting Relative Paths with super

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/rustlings-course#183]
The text says, "...so we can use super to go to the parent module of back_of_house, which in this case is `crate`, the root." But as the accompanying code is laid out, the structure looks more like, `crate::front_of_house::serving::back_of_house`. Therefore, relative to back_of_house the parent (super) is the `serving` module. 

Fwiw, the rust book (listing 7-8) has a slightly different example so the text makes sense in that case (ie `crate` is indeed the root)

**Comment by sofiiako** [comment]
@bravit could you please take a look at this? Thanks!
