### ISSUE TITLE
Problem definition is out of sync with rustlings Generic Types Traits and Lifetime / Traits / Compare Licenses

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/rustlings-course#184]
The problem is out of sync with the [source](https://github.com/rust-lang/rustlings/blob/e3af483fa68dbe2efd957327500b55acd86ef0fd/exercises/traits/traits4.rs#L10-L12)

In the original source, the `Licensed` trait definition has a default implementation. This makes sense since you are asked to modify _only_ the last two lines of the exercise.

As a result, this below wont work _without_ actually implementing it in the actual exercise

```rust
pub trait Licensed {
    fn licensing_info(&self) -> String;
}
```

**Comment by sofiiako** [comment]
@bravit I assume this modification was intentional and we can close this?

**Comment by bravit** [comment]
I've realized I don't understand how dependency placeholders work. I somehow thought that they automatically transfer solved placeholders from the previous task. I'll fix this.
