### ISSUE TITLE
Strings and &strs error: "File not included in module tree, analysis is not available"

### ISSUE THREAD

**Issue by drhaynes** [jetbrains-academy/rustlings-course#19]
In task: Common Collections -> String Test -> Strings and strs.

Seems to be a missing configuration somewhere, resulting in the error "File not included in module tree, analysis is not available" and not being able to run the tests to 'Check' answers.

When trying to check answers, the Task view shows error: "Failed to find package for 'Strings and strs' task.

**Comment by igalimov** [comment]
Hello @drhaynes,
Thank you for your feedback.

I was able to pass the tests in the *Strings and strs* task.
Could you please try to update the project in **VCS | Update Project**?

Please let me know if it helps.

**Comment by dorianpula** [comment]
Hi @igalimov I can confirm that working with a new copy of the lessons, that the issue was fixed.  (I ran into the same problem earlier but @drhaynes posted the problem first)

**Comment by drhaynes** [comment]
Just to send this, yes, after updating, confirmed working.
