### ISSUE TITLE
Failed to Launch Checking Common Programming Concepts / Basic Data Types / Numeric Test

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/rustlings-course#197]
I am unable to check my work, because I am told that it "failed to launch checking"

**Comment by Geravant** [comment]
Should be fixed by [this](https://youtrack.jetbrains.com/issue/EDU-5608/java.lang.NoSuchMethodError-on-checking-Rust-projects). The solution is to update to the latest plugin version.
