### ISSUE TITLE
Failed to launch checking. For more information, see the Troubleshooting guide Common Programming Concepts / Repetitions / Find a sum

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/rustlings-course#198]
Can't check questions, even without errors.

**Comment by Geravant** [comment]
Should be fixed by [this](https://youtrack.jetbrains.com/issue/EDU-5608/java.lang.NoSuchMethodError-on-checking-Rust-projects). The solution is to update to the latest plugin version.
