### ISSUE TITLE
Course already solved

### ISSUE THREAD

**Issue by Sroka** [jetbrains-academy/rustlings-course#20]
It seems that the course exercises are already solved in this repo. E.g. in 

> Understanding Ownership/Move Semantics/Borrow/src/main.rs

the exercise is to make it compile. When I open the file and click Check the file already compiles so there is nothing to do there really. It seems that for this particular case the unnecessary fixes were done in commits d09f09f61a407c7ef745ecd7d0b768f718b54f84 and 28f63ef5352ad4732c9378a3003cb5c7bd97c92b.

Is it just me or or does this completely misses the point of the course?

**Comment by igalimov** [comment]
Hello @Sroka,
Thank you for your feedback.

It looks like the course has been opened in the Educator Mode.
If so, please try putting this course into the Learner Mode by going to **File | Course Creator | Create Course Preview**.

Please let me know if it helps.

**Comment by GauthierPLM** [comment]
I am not sure if it's the same issue, but I can confirm that some steps auto validate themselves without any user modifications, such as About and Installation from Introduction > Getting started.

I am not sure if it is an issue of EduTools or this course, but having a way to indicate that a task is only a description and its code' only purpose is to illustrate the description would fix the issue.
It is a bit disturbing to have the task solved without any action, or without any code in it (in the above mentioned tasks, the function does not contain anything).

**Comment by igalimov** [comment]
Hello @GauthierPLM,
Thank you for pointing us to this.

We are thinking of re-designing the "text tasks" and we have this feature request on YouTrack:
https://youtrack.jetbrains.com/issue/EDU-2928.

Please feel free to upvote the issue and post your comments/suggestions.

**Comment by rohandhruva** [comment]
As @Sroka mentioned, I had the same problem: when I opened the course, by default it opened with all the solutions already filled in. I could switch to the "create course preview" you suggested, @igalimov , but instead I just deleted the project and reopened it. That "fixed" the issue and this time it opened without the solutions.
