### ISSUE TITLE
Check button not working Common Programming Concepts / Basic Data Types / Numeric Test

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/rustlings-course#200]
When i go to check solution, it says Failt to launch cheking. For more infomation, see the Troubleshooting guide

**Comment by Geravant** [comment]
Should be fixed by [this](https://youtrack.jetbrains.com/issue/EDU-5608/java.lang.NoSuchMethodError-on-checking-Rust-projects). The solution is to update to the latest plugin version.
