### ISSUE TITLE
Won't check solution Common Programming Concepts / Tuples and Arrays / Create an Array

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/rustlings-course#201]
When i go to chek colution this error appears: "Failed to launch checking. For more information, see the Troubleshooting guide"

**Comment by Geravant** [comment]
Should be fixed by [this](https://youtrack.jetbrains.com/issue/EDU-5608/java.lang.NoSuchMethodError-on-checking-Rust-projects). The solution is to update to the latest plugin version.
