### ISSUE TITLE
It won't launch the check Common Programming Concepts / Repetitions / Print Months

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/rustlings-course#204]
Multiple times when I try to check a piece of code(That I know works) it fails to launch checking, but then on other excercises it works again.

**Comment by Geravant** [comment]
@guenzelandreas , thank you for your report! This is extremely helpful for identifying the problem. Could you please share what OS do you have?

**Comment by Geravant** [comment]
@guenzelandreas , thanks again!
Yes, we were having an issue with one of our testing subsystems (which is common spot for the tasks you described). It was indeed fixed in [our latest release](https://youtrack.jetbrains.com/issue/EDU-5608/java.lang.NoSuchMethodError-on-checking-Rust-projects)
