### ISSUE TITLE
Failed to run 'Check' Common Programming Concepts / Basic Data Types / Numeric Test

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/rustlings-course#205]
Failed to run the Check command on this. I get the following error:
'Failed to launch checking. For more information, see the Troubleshooting guide'
Additional thing, the link to the Troubleshooting guide opens a 404 not found error page.

**Comment by Geravant** [comment]
Should be fixed by [this](https://youtrack.jetbrains.com/issue/EDU-5608/java.lang.NoSuchMethodError-on-checking-Rust-projects). The solution is to update to the latest plugin version.
