### ISSUE TITLE
 Common Programming Concepts / Repetitions / Print Months

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/rustlings-course#206]
Failed to launch checking
Failed to launch checking. For more information, see the Troubleshooting guide

build:
C:/Users/<user-name-replaced>/.cargo/bin/cargo.exe build --color=always --message-format=json-diagnostic-rendered-ansi --bin print_months --manifest-path "D:\Learning\Courses\JetBrains\Learn Rust\Common Programming Concepts\Repetitions\Print Months\Cargo.toml"
   Compiling print_months v0.1.0 (D:\Learning\Courses\JetBrains\Learn Rust\Common Programming Concepts\Repetitions\Print Months)
    Finished dev [unoptimized + debuginfo] target(s) in 1.60s
Process finished with exit code 0

**Comment by Geravant** [comment]
Should be fixed by [this](https://youtrack.jetbrains.com/issue/EDU-5608/java.lang.NoSuchMethodError-on-checking-Rust-projects). The solution is to update to the latest plugin version.
