### ISSUE TITLE
code reset Understanding Ownership / What is ownership / Who Owns the One Ring

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/rustlings-course#216]
when i reset the code the base problem is no where to be found and the .rs file is empty

**Comment by sofiiako** [comment]
Could be related to this https://youtrack.jetbrains.com/issue/EDU-5568/All-solutions-are-shown-to-the-student-in-a-FW-lesson-after-pressing-reset-content-button

**Comment by DanielMcCord** [comment]
I seem to encounter this issue at the same time as #235

**Comment by kochaika** [comment]
Seems to be fixed in #284
