### ISSUE TITLE
All tasks fail to execute Writing Automated Tests / How to Write Tests / Assert_Eq

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/rustlings-course#217]
When clicking on the "Check" button in CLion, all tasks fail with "Execution failed" whereas their implementation are correct.

**Comment by sofiiako** [comment]
Hi! We could not reproduce this. Could you please provide IDE logs?

**Comment by kochaika** [comment]
Can't reproduce, no extra info provided. Try to use the latest version of Academy plugin and Rust course
