### ISSUE TITLE
Incorrect step type Structs Methods Enums and Pattern Matching / Structs / Adding Useful Functionality with Derived Traits

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/rustlings-course#220]
The step looks like a completed task even though it is intended as purely theoretical.

**Comment by vasartam** [comment]
The screenshot of the problem. The elements highlighted signify the step as a task.

![2023-03-11_16-54-37](https://user-images.githubusercontent.com/15614336/224488908-f3f35324-4714-4e17-b266-9fc2d748fbd1.png)

**Comment by sofiiako** [comment]
Hi @vasartam! This was done just to highlight parts of the code that students need to pay special attention to. We are thinking about implementing a different way of highlighting that would not cause such confusion.
