### ISSUE TITLE
Incorrect step type Modules / Modules / Paths for Referring to an Item in the Module Tree

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/rustlings-course#222]
The step looks like a completed task even though it is intended as purely theoretical.

**Comment by vasartam** [comment]
This is almost the same as #220

**Comment by sofiiako** [comment]
Hi @vasartam! This was done just to highlight parts of the code that students need to pay special attention to. We are thinking about implementing a different way of highlighting that would not cause such confusion.
