### ISSUE TITLE
The paragraph after the code run result snippet is merged with it Error Handling / Error Handling / Using a panic Backtrace

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/rustlings-course#234]
The paragraph starting with "This error points at a file we didn’t write..." is merged with a code block above it.

**Comment by vasartam** [comment]
Screenshot of the problem:

<img width="764" alt="image" src="https://user-images.githubusercontent.com/15614336/230785576-3f013b1f-2c46-4672-b095-1185eb98d72d.png">

**Comment by sofiiako** [comment]
@vasartam Thank you!
