### ISSUE TITLE
Solution not checked Understanding Ownership / The Slice Type / Understanding Types

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/rustlings-course#240]
A task is given but the check doesn't actually test anything. You can comment out the entirety of the main function's body and the check will pass.
Additionally, the description of the task alludes to a function in IDEA to find the types, but it doesn't specify what that function is or how to access it.
N/A

**Comment by bravit** [comment]
I'm not sure about the second issue:
>  Additionally, the description of the task alludes to a function in IDEA to find the types, but it doesn't specify what that function is or how to access it.

For me, the shortcut is shown in both CLion and IDEA (macOS).
