### ISSUE TITLE
"Check" doesn't work Common Programming Concepts / Basic Data Types / Numeric Test

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/rustlings-course#249]
When I press the Check button Java IDE says "Failed to launch checking. For more information, see the Troubleshooting guide".
I can Run exercises, but can't Check them.
Failed to launch checking. For more information, see the Troubleshooting guide

**Comment by kochaika** [comment]
Looks like is duplicate #248 issue. Already fixed
