### ISSUE TITLE
Failed to launch checking. For more information, see the Troubleshooting guide Common Programming Concepts / Variables / New Variable Binding

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/rustlings-course#253]
I'm using "Learn Rust" and when i click the button "Check" in the Task window the following message is displayed: "Failed to launch checking. For more information, see the Troubleshooting guide."
I went to see the Troubleshooting guide but I did not find anything to correct this error.

**Comment by edziegle** [comment]
Looks to be the same issue as #248

**Comment by kochaika** [comment]
Looks like it is duplicate #248 issue. Already fixed
