### ISSUE TITLE
Check Fail Introduction / Getting started / Hello World

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/rustlings-course#257]
Hi! On the Rust course I initially followed all the installation steps and on the first task Check I get the following message: "Failed to launch checking. For more information, see the Troubleshooting guide". On the guide page there's no section for Rust. How I can actually run the Checks?
Failed to launch checking. For more information, see the Troubleshooting guide

**Comment by kochaika** [comment]
Looks like it is duplicate #248 issue. Already fixed
