### ISSUE TITLE
Failed to launch checking on installation from scratch Introduction / Getting started / Hello World

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/rustlings-course#260]
Failed to launch checking. For more information, see the Troubleshooting guide
Build worked, cargo packages was imported as expected and code is executed

/Users/alonso.zuniga/.cargo/bin/cargo build --color=always --message-format=json-diagnostic-rendered-ansi -p hello_macro_derive
   Compiling proc-macro2 v1.0.58
   Compiling quote v1.0.27
   Compiling syn v1.0.109
   Compiling hello_macro_derive v0.1.0 (/Users/alonso.zuniga/IdeaProjects/Learn Rust/Macros/Procedural Macros/hello_macro_derive)
    Finished dev [unoptimized + debuginfo] target(s) in 7.42s
Process finished with exit code 0

/Users/alonso.zuniga/.cargo/bin/cargo run --color=always --bin hello_world --manifest-path "/Users/alonso.zuniga/IdeaProjects/Learn Rust/Introduction/Getting started/Hello World/Cargo.toml"
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
     Running `target/debug/hello_world`
Hello, world!

Process finished with exit code 0

**Comment by kochaika** [comment]
Looks like it is duplicate #248 issue. Already fixed
