### ISSUE TITLE
Clippy marks question code as incorrect Understanding Ownership / What is ownership / Who Owns the One Ring

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/rustlings-course#272]
With Clippy enabled, the IDE shows an error (red underline) for this section of code:
```
    let sam = frodo;
    let frodo = sam;
```
It complains that it looks like the code is trying to swap the two variables, and that I should use `std::mem::replace` instead. The check in the Description window continues to succeed as expected in spite of the error in the editor.

**Comment by DaniilBogdanovJB** [comment]
The problem was reproduced. 
Issue on YouTrack created: https://youtrack.jetbrains.com/issue/EDC-833/Rustling-Course-Understanding-Ownership-What-is-ownership-Who-Owns-the-One-Ring-Clippy-underlines-correct-answer
