### ISSUE TITLE
Not enough hints, add third hint Understanding Ownership / References and Borrowing / Move Borrow Mutate or What

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/rustlings-course#279]
After completing the task you have to change code outside "changed zone"
error[E0308]: mismatched types
  --> Understanding Ownership/References and Borrowing/Move, Borrow, Mutate, or What/src/main.rs:15:11
   |
14 | fn uppercase_and_print(mut msg: char) {
   |                                 ---- expected due to this parameter type
15 |     msg = msg.to_uppercase(); // .to_string().parse().unwrap()
   |           ^^^^^^^^^^^^^^^^^^ expected `char`, found `ToUppercase`
   |
help: try removing the method call
   |
15 -     msg = msg.to_uppercase(); // .to_string().parse().unwrap()
15 +     msg = msg; // .to_string().parse().unwrap()
   |

**Comment by bravit** [comment]
This is not a bug. The solution provided by the commenter here is incorrect. Writing `mut msg: String` instead of `mut msg: char` fixes it. I don't think there is a need for an additional hint.
