### ISSUE TITLE
Interacting with task breaks "Peek solution..." and "Reset Content" after IDE restart

### ISSUE THREAD

**Issue by DanielMcCord** [jetbrains-academy/rustlings-course#284]
**Steps to reproduce**
1. Interact with one or more tasks: For a programming task, use the "Check" or "Reset Content" buttons. For a theory task, just viewing the task is sufficient. To my knowledge, this course does not have quiz tasks.
1. Restart the IDE.
1. Attempt to use "Peek solution..." and/or "Reset Content" on the same task(s) you interacted with.

**Expected behavior**
"Peek solution..." reveals the correct answer and shows the diff, and "Reset Content" restores the original content of the file(s) in the task.

**Actual behavior**
"Peek solution..." does nothing. "Reset Content" blanks out all .rs files in the task (curiously, the Cargo.toml, if present, is reset correctly). Broken behavior persists across IDE restarts.

**Other infomation**
- Only happens when using JetBrains Academy 2022.7 ([changelog](https://youtrack.jetbrains.com/issues?q=project%3A+%7BJetbrains+Academy%7D+Fix+versions%3A+2022.7)) or newer.
- Specific to this course.
- Affects both current and old versions of the course.

**Workaround**
Switch back and forth between two installs of the IDE:
- A 2022.1.* IDE with JetBrains Academy 2022.6-2022.1-569 ([download page](https://plugins.jetbrains.com/plugin/10081-jetbrains-academy/versions/stable/193366)) - used to track course progress, and reliably access the "Peek solution..." and "Reset Content" features.
- A newer IDE such as 2023.2.* - used to work on separate copy of exercise with up-to-date Rust plugin.

#235 and #216 seem to be duplicates of this issue.

**Comment by DaniilBogdanovJB** [comment]
Hello @DanielMcCord ,

I can't reproduce the issue with the latest IDEA, Rust and Academy plugins. Could you please re-download the course and check if the issue is still reproducible? 

If it does, please clarify the lesson which we can check and the steps for reproducing. Also, what OS you are using?

**Comment by DanielMcCord** [comment]
@DaniilBogdanovJB Switching to the [proprietary Rust plugin](https://plugins.jetbrains.com/plugin/22407-rust) fixes it for me, using the latest CLion on Linux Mint.

Note: JetBrains Academy 2023.9 dropped support for using the deprecated [open-source Rust plugin](https://plugins.jetbrains.com/plugin/8182--deprecated-rust) to start the Learn Rust course.
