### ISSUE TITLE
Wrong solution checks out Understanding Ownership / What is ownership / More Exclamations without Arguments

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/rustlings-course#285]
Solution for "More Exclamations" also incorrectly checks out for "More Exclamations without Arguments"

**Comment by DaniilBogdanovJB** [comment]
Issue reproduced and created one on YouTrack:https://youtrack.jetbrains.com/issue/EDC-863/Learn-Rust-Understanding-Ownership-What-is-ownership-More-Exclamations-without-Arguments-Check-accepts-solution-from-More
