### ISSUE TITLE
This problem is complete mess Structs Methods Enums and Pattern Matching / Structs with Methods / Sending Packages

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/rustlings-course#287]
I can't even comprehend what is going on in this code. I get the general idea and I've understood the requirements, but formatting of code and placeholders is what makes this problem unsolvable to me :/
-

**Comment by sofiiako** [comment]
Hi! Thank you for your feedback! We are trying our best to present our learning materials in a clear and concise way. Please let us know if you have any specific suggestions on how to make them better. You can also contribute by making a pull request to this repository :)
