### ISSUE TITLE
Awful description Common Collections / Options / Use Option

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/rustlings-course#288]
I always just assume that it's just me being stupid first, but... This problem itself is plain simple, but description really makes it hard to even comprehend what do you want me to do -__-
-

**Comment by sofiiako** [comment]
Hi! Thank you for your feedback! We are trying our best to present our learning materials in a clear and concise way. Please let us know if you have any specific suggestions on how to make them better. You can also contribute by making a pull request to this repository :)
