### ISSUE TITLE
This is just lazy Standard Library Types / Smart Pointers / Intro

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/rustlings-course#289]
Now you don't even try to give theory at this point (I believe you've just ctrl-c/ctrl-v'ed previous theory sections). You just say "go read the book". Hilarious :)
-

**Comment by sofiiako** [comment]
Hi! Thank you for your feedback! We are trying our best to present our learning materials in a clear and concise way. Please let us know if you have any specific suggestions on how to make them better. You can also contribute by making a pull request to this repository :)
