### ISSUE TITLE
bug: "Error Handling/Error Handling/Matching on Different Errors" doesn't open a course  "Iterators and Closures"

### ISSUE THREAD

**Issue by Tsovak** [jetbrains-academy/rustlings-course#292]
In the section "Error Handling/Error Handling/Matching on Different Errors" we have to click to the line  "Iterators and Closures".

**Actual behavior:**
both of the links don't navigate to the correct page of the course.

**Expected behaviour:**
A users navigates to the page by clicking on the link..

Course-remote-info:
```
id: 16631
update_date: "Mon, 10 Jul 2023 09:35:10 UTC"
course_version: 19
```

RustRover 2023.3 EAP
Build #RR-233.13135.127, built on January 23, 2024
Expiration date: March 23, 2024
Runtime version: 17.0.9+7-b1087.9 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
  run.processes.with.pty=false
  ide.experimental.ui=true
  transferSettings.vscode.onlyCargoToml=true
  llm.ai.assistant.toolwindow.activation.on.start=false
Non-Bundled Plugins:
  com.jetbrains.edu (2024.1-2023.3-882)
  com.intellij.ml.llm (233.13135.116)
  com.github.copilot (1.4.13.4415)

**Comment by kochaika** [comment]
Hi!
Thanks a lot for the report!
