### ISSUE TITLE
Update to the latest 4.0.0 upstream rustlings course

### ISSUE THREAD

**Issue by rohandhruva** [jetbrains-academy/rustlings-course#37]
Hello, 

Thank you so much for making this course available in CLion edutools! Would it be possible to update the course content to the latest 4.0.0 that was released a few weeks back? 

The [changelog](https://github.com/rust-lang/rustlings/blob/main/CHANGELOG.md#400-2020-07-08) seems tempting enough to warrant an upgrade :)

**Comment by Geravant** [comment]
Hello, @rohandhruva , sorry for such a long response!
Thank you for your feedback - we were really past due with the update, but now the course is available at https://plugins.jetbrains.com/plugin/16631-rustlings with the materials from 4.3.0 rustlings update and we are testing the 4.4.0 at the moment. We will try better to keep up.
