### ISSUE TITLE
Line Number Mismatch on Borrow Task

### ISSUE THREAD

**Issue by indo-dev-0** [jetbrains-academy/rustlings-course#38]
There is nothing on Line #7:

![Screenshot from 2020-08-20 14-00-23](https://user-images.githubusercontent.com/53309859/90825494-db254200-e2ed-11ea-9c9c-f0a1f05b3010.png)

**Comment by Geravant** [comment]
@indo-dev-0 , I am sorry for such a long response.
Thank you for your feedback - the line numbers in the description is [fixed](https://github.com/jetbrains-academy/rustlings-course/commit/a3cdc56512e8dbdc1b92119f133e3218387a2f7c) now, including the hint
