### ISSUE TITLE
Structs should be explained before explaining macros, modules, etc

### ISSUE THREAD

**Issue by aminya** [jetbrains-academy/rustlings-course#39]
Structs are an essential part of the language but they are not explained until the end. The macros should be IMO the last chapter that is explained.

**Comment by Geravant** [comment]
@aminya , I do apologize for such a long response.
Thank you for your feedback - you were absolutely right, the **Structs** section should be introduced earlier. We fixed this in our last commutative update, particularly in [this commit](https://github.com/jetbrains-academy/rustlings-course/commit/7a1c4cef15287c65f2b35388ead59fc0a7ef0f35)
